### ISSUE TITLE
Question: output file

### ISSUE THREAD

**Issue by brunano21** [poppinlp/grunt-htmlhint-plus#1]
Hi, 
is there a chance to get the output in a file or ready for a reporter?

Thanks!

**Comment by poppinlp** [comment]
OK，i'll do it.

**Comment by brunano21** [comment]
Well, would be useful if the plugin provides a reporter, via XML (in different formats, like the ones in [grunt-contrib-csslint](https://github.com/gruntjs/grunt-contrib-csslint#formatters) or even better through a HTML page.

**Comment by obrejla** [comment]
How does it look like? Checkstyle reporter would be great as well (see [checkstyle-formatter](https://www.npmjs.com/package/checkstyle-formatter)). Thanks.

**Comment by willsteinmetz** [comment]
@brunano21 @obrejla Looking at the help for the [htmlhint](https://github.com/yaniswang/HTMLHint) node module that this plug-in uses, it looks like the options for output are the default, json, junit, and checkstyle when using it on the command line. However, doing it via node responds with a JSON object with a fair amount of info for each notice.

It looks like each output format would have to be handled individually. It already returns JSON so that wouldn't be a difficult one to produce. A simple text file would also be easy to produce as it would essentially be what is output to the console but just in a file instead. The checkstyle-formatter could easily be used for that format. I'm not sure about the other formats. While I say easy, it would still involve some time and I can see the value of trying to create a pull request for it after the one I just created gets accepted/rejected. I'll give it a try and see if I can do it because that would be useful for projects we use this on at work.
